cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
      dir: Gyunny/
    region:
      static: ${AWS_REGION}
    stack:
      auto: false